# Generated by Django 3.1.7 on 2021-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.DecimalField(db_column='postal_code', decimal_places=0, max_digits=6),
        ),
    ]
