# Generated by Django 3.1.7 on 2021-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0004_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='transaction_id',
            field=models.TextField(db_column='transaction_id', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='money',
            unique_together={('money_id', 't_time')},
        ),
    ]
