# Generated by Django 3.1.7 on 2021-03-26 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0006_auto_20210326_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('stationery_id', models.IntegerField(db_column='stationery_id', max_length=50, primary_key=True, serialize=False)),
                ('stationery_name', models.CharField(db_column='stationery_name', max_length=50)),
                ('tot_quantity', models.IntegerField(blank=True, db_column='tot_quantity', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('location_id', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dorei.location')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.IntegerField(blank=True, db_column='grade', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='bookdonate',
            name='is_collected',
            field=models.BooleanField(db_column='is_collected', default=False),
        ),
        migrations.CreateModel(
            name='StationeryDonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField(db_column='t_time')),
                ('quantity', models.IntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_collected', models.BooleanField(db_column='is_collected', default=False)),
                ('stationery_id', models.ForeignKey(db_column='stationery_id', on_delete=django.db.models.deletion.CASCADE, to='dorei.stationery')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dorei.user')),
            ],
            options={
                'unique_together': {('user_id', 'stationery_id', 't_time')},
            },
        ),
    ]
