# Generated by Django 3.1.7 on 2021-03-27 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0008_auto_20210326_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationeryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField(db_column='t_time')),
                ('quantity', models.IntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_delivered', models.BooleanField(db_column='is_delivered', default=False)),
                ('stationery_id', models.ForeignKey(db_column='stationery_id', on_delete=django.db.models.deletion.CASCADE, to='dorei.stationery')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dorei.user')),
            ],
            options={
                'unique_together': {('user_id', 'stationery_id', 't_time')},
            },
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField(db_column='t_time')),
                ('is_delivered', models.BooleanField(db_column='is_delivered', default=False)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, to='dorei.book')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dorei.user')),
            ],
            options={
                'unique_together': {('user_id', 'isbn')},
            },
        ),
    ]
