# Generated by Django 3.1.7 on 2021-03-27 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0009_bookrequest_stationeryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='stationery_id',
            field=models.AutoField(db_column='stationery_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationeryrequest',
            name='quantity',
            field=models.IntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
