# Generated by Django 3.1.7 on 2021-03-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0010_auto_20210327_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_number', models.DecimalField(db_column='phone_number', decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dorei.user')),
            ],
            options={
                'unique_together': {('user_id', 'phone_number')},
            },
        ),
    ]
